### PR TITLE
Switch code coverage to babel-istanbul

### LINKED ISSUE #189: isparta now unmaintained... switch to babel-istanbul?
I appreciate the example you've given here as it's helped me in writing my own React tests and producing code coverage.

I noticed that the [`isparta`](https://github.com/douglasduteil/isparta) package now has the "No Maintenance Intended" banner, and it looks like [`babel-istanbul`](https://github.com/jmcriffey/babel-istanbul) might now be more active.  After testing the switch on my own project, the coverage result appears to be the same.  You may just need to change this command in a couple places in your `package-scripts.js`:

``` sh
npm install --save babel-istanbul

# then change from
babel-node node_modules/isparta/bin/isparta cover

# to
babel-istanbul cover
```

### PR DESCRIPTION
**Pull request by tribou**
Fixes #189 

Unfortunately, this may not be a clean swap.  First, `babel-istanbul` wasn't picking up the `.babelrc` webpack plugin, so I had to run it through `babel-node` first.  Second, the code coverage is now different. 😕 

Before:

```
-------------------------------------------|----------|----------|----------|----------|----------------|
File                                       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------------------|----------|----------|----------|----------|----------------|
 react-component-template/                 |    94.74 |       60 |      100 |    94.74 |                |
  webpack.config.js                        |    94.74 |       60 |      100 |    94.74 |             12 |
 react-component-template/src/             |    88.89 |      100 |       50 |       80 |                |
  ReactComponentTemplate.js                |    88.89 |      100 |       50 |       80 |              7 |
 react-component-template/src/example/App/ |    91.67 |      100 |       50 |    83.33 |                |
  index.js                                 |    91.67 |      100 |       50 |    83.33 |              8 |
-------------------------------------------|----------|----------|----------|----------|----------------|
All files                                  |     92.5 |    84.62 |       50 |       90 |                |
-------------------------------------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 92.5% ( 37/40 )
Branches     : 84.62% ( 11/13 ), 1 ignored
Functions    : 50% ( 2/4 )
Lines        : 90% ( 27/30 )
================================================================================
```

After:

```
-------------------------------------------|----------|----------|----------|----------|----------------|
File                                       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------------------|----------|----------|----------|----------|----------------|
 react-component-template/                 |    94.74 |       60 |      100 |    94.74 |                |
  webpack.config.js                        |    94.74 |       60 |      100 |    94.74 |             12 |
 react-component-template/src/             |       80 |      100 |        0 |       80 |                |
  ReactComponentTemplate.js                |       80 |      100 |        0 |       80 |              7 |
 react-component-template/src/example/App/ |    83.33 |      100 |        0 |    83.33 |                |
  index.js                                 |    83.33 |      100 |        0 |    83.33 |              9 |
-------------------------------------------|----------|----------|----------|----------|----------------|
All files                                  |       90 |       60 |        0 |       90 |                |
-------------------------------------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 90% ( 27/30 )
Branches     : 60% ( 3/5 )
Functions    : 0% ( 0/2 )
Lines        : 90% ( 27/30 )
================================================================================
```

I went ahead and submitted this PR for reference, but I don't think this should be merged yet.

### CODE REVIEW

**Comment by tribou** [comment]
I'm wondering if it may have something to do with jmcriffey/babel-istanbul#56, but the proposed solutions didn't fare any better.

**Comment by nkbt** [comment]
Maybe we don't need `babel-node` for babel-istanbul, I don't remember correctly

**Comment by tribou** [comment]
I was able to remove `babel-node` after I realized it was excluding the `test/` dir by default.  However, now the coverage is only picking up the `test/index.js` script:

```
-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
 test/     |      100 |      100 |      100 |      100 |                |
  index.js |      100 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
All files  |      100 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 100% ( 2/2 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 2/2 )
================================================================================
```

I tried adding `babel-plugin-__coverage__`, but it produced the same result.

**Comment by nkbt** [comment]
Thanks @tribou!

**Pull request closed without merging**
